version: '3.3'

services:
  app:
    image: desmond2_eval_container_clustering
    container_name: desmond2_eval_container_clustering
    build: .
    volumes:
      - type: bind
        source: ~/DESMOND2_benchmarking/
        target: /tmp/
volumes:
  desmond2-eval-volume: